import type {Metadata} from 'next';
import data from '@/lib/content.json';
import {PageHero,Eyebrow,ContactBand,PeoplePreview} from '@/components/site/content';
import {Entrance} from '@/components/site/entrance';
import {asset} from '@/lib/asset';
export const metadata:Metadata={title:'The Firm',description:'Meet Ducrest Partners, a Nigerian law firm focused on intellectual property, technology and the creative economy.'};
export default function Firm(){return <>
 <PageHero label="The firm" title={<>Proven Expertise<br/><em>with Global Perspective</em></>} description={data.positioning}/>
 <section className="wrap section story-grid" id="about"><div><Eyebrow>About Ducrest</Eyebrow><h2>Protecting the value<br/><em>of your work.</em></h2><figure className="firm-office-portrait"><img src={asset('/images/ducrest-partners-office.webp')} alt="Two Ducrest Partners lawyers in the firm's office" width="1280" height="1024"/></figure></div><div className="prose">{data.about.map((p,i)=><p className={i===0?'lead':undefined} key={p}>{p}</p>)}</div></section>
 <section className="purpose section" id="purpose"><div className="wrap purpose-grid"><Entrance><Eyebrow>Our mission</Eyebrow><h2>Legal architecture<br/><em>for enterprise.</em></h2><p>{data.mission}</p></Entrance><Entrance><Eyebrow>Our vision</Eyebrow><h2>Lasting value.<br/><em>Across generations.</em></h2><p>{data.vision}</p></Entrance></div></section>
 <section className="wrap section" id="values"><div className="section-heading"><div><Eyebrow>Our values</Eyebrow><h2>The standards<br/><em>behind our work.</em></h2></div></div><p className="values-intro">{data.valuesIntro}</p><div className="value-list">{data.values.map((v,i)=><div className="value-row" key={v.title}><span className="service-number">0{i+1}</span><h3>{v.title}</h3><p>{v.body}</p></div>)}</div></section><section className="origin-story section" id="our-story"><div className="wrap"><Eyebrow light>Our story</Eyebrow><h2>Four Pillars.<br/><em>One Conviction.</em></h2><div className="origin-grid">{data.story.slice(0,3).map(chapter=><article key={chapter.title}><h3>{chapter.title}</h3><div className="prose">{chapter.paragraphs.map(p=><p key={p}>{p}</p>)}</div></article>)}</div><div className="pillar-grid">{data.pillars.map((pillar,i)=><article key={pillar.title}><span className="service-number">0{i+1}</span><h3>{pillar.title}</h3><p className="pillar-summary">{pillar.summary}</p><p>{pillar.body}</p></article>)}</div><div className="origin-engine prose"><h3>{data.story[3].title}</h3>{data.story[3].paragraphs.map(p=><p key={p}>{p}</p>)}<p className="origin-conviction">We did not stumble into this industry.<br/><em>We chose it.</em></p></div></div></section><section className="wrap section" id="reach"><Eyebrow>Our reach</Eyebrow><h2>Local Execution.<br/><em>International Reach.</em></h2><p className="reach-intro">{data.reach}</p><div className="reach-grid">{data.reachItems.map(item=><article key={item.title}><h3>{item.title}</h3><p>{item.body}</p></article>)}</div></section><PeoplePreview/><ContactBand/>
 </>}
