import {BrandLogo} from './logo';
import {asset} from '@/lib/asset';
import Link from 'next/link';
import {ArrowUpRight} from 'lucide-react';
import type {ReactNode} from 'react';
import data from '@/lib/content.json';
export function Eyebrow({children,light=false}:{children:ReactNode;light?:boolean}){return <p className={'eyebrow'+(light?' light':'')}>{children}</p>}
export function PageHero({label,title,description}:{label:string;title:ReactNode;description?:string}){return <section className="page-hero"><div className="wrap"><Eyebrow light>{label}</Eyebrow><h1>{title}</h1>{description&&<p className="hero-description">{description}</p>}</div></section>}
export function ContactBand(){return <section className="contact-band"><div className="wrap"><div><Eyebrow light>Let’s talk</Eyebrow><h2>Let us know how<br/>we can <em>represent you.</em></h2></div><Link href="/contact/" className="button button-light">Contact the firm <ArrowUpRight size={20} aria-hidden="true"/></Link></div></section>}
export function PeoplePreview(){return <section className="people-preview section"><div className="wrap"><div className="section-heading"><div><Eyebrow>Our people</Eyebrow><h2>Experience behind<br/><em>every mandate.</em></h2></div><Link href="/our-people/" className="text-link">Meet our team <ArrowUpRight size={18} aria-hidden="true"/></Link></div><div className="people-grid">{data.people.filter(p=>p.image).map(p=><Link href={'/our-people/#'+p.name.toLowerCase().replaceAll(' ','-')} className="person-preview" key={p.name}><div className="portrait"><img src={asset('/images/'+p.image)} alt={p.name} width="608" height="680" loading="lazy"/></div><div className="person-label"><div><h3>{p.name}</h3><p>{p.role}</p></div><ArrowUpRight size={23} aria-hidden="true"/></div><p className="person-focus">{p.focus}</p></Link>)}</div></div></section>}
export function Footer(){return <footer className="site-footer"><div className="wrap"><div className="footer-top"><div><Link className="footer-name footer-brand" href="/" aria-label="Ducrest Partners — Home"><BrandLogo/></Link><p>We Protect. We Build. We Defend.</p></div><div><span className="footer-label">Explore</span><nav aria-label="Footer navigation"><Link href="/the-firm/">The Firm</Link><Link href="/expertise/">Expertise</Link><Link href="/our-people/">Our People</Link><Link href="/sectors/">Sectors</Link><Link href="/contact/">Contact</Link></nav></div><div><span className="footer-label">Get in touch</span><a href="mailto:info@ducrestpartners.com">info@ducrestpartners.com</a><a href="tel:+2348101632500">+234 810 163 2500</a><p>Lagos & Abuja, Nigeria</p></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Ducrest Partners</span><div><Link href="/legal-notice/">Legal Notice</Link><Link href="/privacy/">Privacy Policy</Link><Link href="/terms-of-use/">Terms of Use</Link><Link href="/disclaimer/">Disclaimer</Link></div><div><a href="https://www.linkedin.com/company/ducrestpartners" target="_blank" rel="noopener noreferrer">LinkedIn</a><a href="https://www.instagram.com/ducrestpartners" target="_blank" rel="noopener noreferrer">Instagram</a></div></div></div></footer>}
