'use client';
import {useState,useRef,type FormEvent} from 'react';
import Link from 'next/link';
import {ArrowUpRight} from 'lucide-react';
import data from '@/lib/content.json';
export function ContactForm(){const [ready,setReady]=useState(false);const [emailDraft,setEmailDraft]=useState('');const result=useRef<HTMLDivElement>(null);
 function prepare(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const message=`Name: ${f.get('name')}\nCompany: ${f.get('company')||'—'}\nEmail: ${f.get('email')}\nTelephone: ${f.get('phone')||'—'}\n\n${f.get('message')}`;setEmailDraft(`mailto:info@ducrestpartners.com?subject=${encodeURIComponent(String(f.get('subject')))}&body=${encodeURIComponent(message)}`);setReady(true);requestAnimationFrame(()=>result.current?.focus())}
 return <form className="enquiry-form" onSubmit={prepare} onChange={()=>setReady(false)}><p className="eyebrow">Send an enquiry</p><h2>Let’s start<br/><em>a conversation.</em></h2><p className="form-intro">Tell us how we can help. Fields marked * are required.</p><div className="form-grid"><label>Full name *<input name="name" autoComplete="name" required maxLength={120}/></label><label>Company / Organisation<input name="company" autoComplete="organization" maxLength={160}/></label><label>Email address *<input name="email" type="email" autoComplete="email" required maxLength={200}/></label><label>Phone number<input name="phone" type="tel" autoComplete="tel" maxLength={40}/></label><label className="full">Subject *<select name="subject" required defaultValue=""><option value="" disabled>Select a practice area or enquiry</option>{data.services.map(s=><option key={s.id}>{s.title}</option>)}<option>General enquiry</option><option>Events & Media</option></select></label><label className="full">Message *<textarea name="message" required maxLength={4000} rows={6} aria-describedby="enquiry-guidance"/></label></div><p id="enquiry-guidance" className="form-note">Please do not include confidential information. Sending an enquiry does not establish an attorney-client relationship. Read our <Link href="/privacy/">Privacy Policy</Link> and <Link href="/disclaimer/">Disclaimer</Link>.</p><button className="button" type="submit">Prepare enquiry <ArrowUpRight size={18}/></button><p className="form-note">You can review your enquiry, then send it through your email application.</p>{ready&&<div className="enquiry-result" ref={result} tabIndex={-1} role="status"><h3>Your enquiry is ready.</h3><p>Nothing has been sent yet. Open the email draft below, review it and send it to info@ducrestpartners.com.</p><a className="text-link" href={emailDraft}>Open email draft <ArrowUpRight size={18}/></a></div>}</form>
}
