'use client';
import Link from 'next/link';
import {BrandLogo} from './logo';
import {usePathname} from 'next/navigation';
import {useState,useEffect,useRef} from 'react';
import {Menu,ArrowUpRight,X,ChevronDown} from 'lucide-react';
import {navigation} from '@/lib/navigation';
import {Sheet,SheetTrigger,SheetContent,SheetTitle,SheetDescription,SheetClose} from '@/components/ui/sheet';
export function Header(){
 const path=usePathname(); const [open,setOpen]=useState(false); const [expanded,setExpanded]=useState<string|null>(null); const [scrolled,setScrolled]=useState(false); const header=useRef<HTMLElement>(null);
 useEffect(()=>{const update=()=>setScrolled(window.scrollY>40);update();window.addEventListener('scroll',update,{passive:true});return()=>window.removeEventListener('scroll',update);},[]);
 useEffect(()=>{const close=(e:PointerEvent)=>{if(!header.current?.contains(e.target as Node))setExpanded(null)};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close)},[]);
 const light=path==='/';
 return <header ref={header} className={'site-header'+(path==='/'?' header-home':'')+(scrolled?' is-scrolled':'')} onKeyDown={e=>{if(e.key==='Escape'&&expanded){header.current?.querySelector<HTMLButtonElement>('[aria-expanded="true"]')?.focus();setExpanded(null)}}}><div className="wrap header-inner"><Link href="/" className="brand" aria-label="Ducrest Partners — Home"><BrandLogo light={light}/></Link>
 <nav className="desktop-nav" aria-label="Main navigation">{navigation.map((item,i)=><div className="nav-group" key={item.href} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setExpanded(current=>current===item.label?null:current)}}><div className="nav-heading"><Link href={item.href} onClick={()=>setExpanded(null)} aria-current={path.startsWith(item.href)?'page':undefined}>{item.label}</Link>{item.children&&<button aria-label={`${item.label} submenu`} aria-expanded={expanded===item.label} aria-controls={`desktop-submenu-${i}`} onClick={()=>setExpanded(expanded===item.label?null:item.label)}><ChevronDown size={14}/></button>}</div>{item.children&&<div id={`desktop-submenu-${i}`} className="nav-dropdown" hidden={expanded!==item.label}><Link href={item.href} className="dropdown-overview" onClick={()=>setExpanded(null)}>Explore {item.label}<ArrowUpRight size={16}/></Link>{item.children.map(child=><Link href={child.href} key={child.href} onClick={()=>setExpanded(null)}>{child.label}</Link>)}</div>}</div>)}<Link className="button" href="/contact/">Contact us <ArrowUpRight size={16}/></Link></nav>
 <div className="mobile-nav"><Sheet open={open} onOpenChange={setOpen}><SheetTrigger asChild><button className="menu-trigger" aria-label="Open navigation"><Menu size={26}/></button></SheetTrigger><SheetContent className="ducrest-menu" showCloseButton={false}><div className="menu-heading"><SheetTitle><BrandLogo/></SheetTitle><SheetClose asChild><button className="menu-trigger" aria-label="Close navigation"><X size={28}/></button></SheetClose></div><SheetDescription className="sr-only">Website navigation</SheetDescription><nav className="mobile-menu-list" aria-label="Mobile navigation"><Link href="/" onClick={()=>setOpen(false)}>Home</Link>{navigation.map(item=>item.children?<details key={item.href}><summary>{item.label}<ChevronDown size={20}/></summary><div><Link href={item.href} onClick={()=>setOpen(false)}>Explore {item.label}</Link>{item.children.map(child=><Link href={child.href} key={child.href} onClick={()=>setOpen(false)}>{child.label}</Link>)}</div></details>:<Link href={item.href} key={item.href} onClick={()=>setOpen(false)}>{item.label}</Link>)}<Link href="/contact/" onClick={()=>setOpen(false)}>Contact us</Link></nav><div className="menu-contact"><a href="mailto:info@ducrestpartners.com">info@ducrestpartners.com</a><a href="tel:+2348101632500">+234 810 163 2500</a></div></SheetContent></Sheet></div></div></header>
}
